/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Tom' at '4/24/17 10:34 AM' with Gradle 2.14.1
 *
 * @author Tom, @date 4/24/17 10:34 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
